language: ruby
rvm:
- 2.1.0
before_script:
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- export JASMINE_SPEC_FORMAT=documentation
env:
  global:
  - PG_USERNAME='postgres'
  - secure: Yxdj+YBr39m14EsNrPK4/jQvTsaTeeh3n5nYJs03izeiUJi4nk+78C8asdN8z3iijZjVSsC594PeNbb9pVj8+ErBghvkwenosuHVzMdrneZajzfHGUEd8NZfmNSHTsmYaK5exqa+5cmlkTSiVYoLBJkB18ZTklcWPf/pvrVZpC8=
  - secure: dV2EAzI3THEnmZI4WaB1/gK1CVb98N6uTQTlJk+46mu9fIBD00AfySJxeF3DMtFFMjopNT6s83XDBaj2yFfi9tcl7UMBHMxs8TsIJiRpePP0hzO9ryxWjQpeHlSvSknAPMXoqGnpM12/bIOISy3otaEzQCYNIsFmTE2/JsTa5/k=
  - secure: g/KVhKbfwXaVH2eKzTwrJMLWlv8F4Q3FI0IGpsTEplV9thJ+nCsvoybGDy/sTlqsiR8tFbUj/oej+8kudEP5RkpVf5rzS7O/fCGUmB/FgYla73EYHBtq8mGWfNBD6MryDmZPkq2baW57uVcQ2Mcks7KHENh8Nnd/ZOmgbHfUpek=
  - secure: kM+uSBi8iTLunetB6OJyrrxUqIgq1Ho+86onka+kUMGwGzxP0wE7JlpKNpq5N5MB2PFXAa+GKu3ztrCeCLG4reFkNbs2kTg8lJ+hLGKFyp/kCdlu5YQozc1hRs+56UBnjRhazNWX/4ShIjkWmO34D9xHSRcVj97iyMU0Q6o8d3Q=
  - secure: RHs9tCxDS749+C/7vCIFqE+UATvVQ23JGe4hzMzUQ5tfK434Snayp0DdizT5Pu5lLx3wnoZzIjXQX21S5Tt0ZifrjlkYYrTkZ+oq0XmGhqOcjR9/rHAFDmV7lym2YSBiL6Lr+b2ZQzcob8g+GUPtmfvO49WA7L0x9IWPKyEyRvA=
  - secure: ZSIWIYgri4F00OEQnWBp0SnCD62T2TPw8T/HcBSkp6XBHI2rJrq9B3rNd643lzVnaYV1pWZFEBOLobZoFCjkrcaY0p8+Rsd3i3T6qd2NINTGmdDpaS7Wfl7mHuqg9PeQWpqtcfI2PIkmtSNrTs4U+OTulOKaUJ43cPb4OGqZ7Ek=
  matrix:
script:
- bundle exec rake db:create
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake spec
