language: ruby
rvm:
- 2.1.0
before_script:
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- export JASMINE_SPEC_FORMAT=documentation
env:
  global:
  - PG_USERNAME='postgres'
  - secure: i5jrnT7ajj8vyVi+DGK8BtDSOsin0N5fZhQi+gMJpz95TeOk0Woa1r9uq0Usc53GIpuGIH8aJqPje1Os28S/rTBjIqerc4O+U9QY18p8XDKveq6KcUdz2KanBTqyaRVGdRt5gCMU/wX/lXd+e7u5jLqZEf0AsPLhZI3B1WW+gfY=
  - secure: h01n/00EXBcgbPlYhOdCQUpZgkj7IPVxOVjIp866oHOZoNJvr29HhguZewDCwEwRzQFNG+6zVV1mk0gf+Pq5XxCrpVxeMPGW3kiTI83kRd0hlzPyFElbnQeGLgd+1I/SAUsO++45EosJTyf2YlKmV4ksER382fu/Uu0LHn4NkP4=
  - secure: fqLq5RcqiPC4i23tiHCv7iRlsfK2d6cJ7uuQY+9oECX3dFMOFXbvkJKxp8PASL08tSjTuNZsKe90O8ttqQqQPoGgAJSBOkd+Gzqgc94nTp4BU3duvsrAM24/YQYYhRs8Riph93fQs2cfWTcgpi/h7aMFwE9vTG+iEPLT2Rg3bc4=
  - secure: l0aVv3dn4ND9LVy2AiGvsx3Ikv7MOdaplOOcUbdm5VliS6y3AWILIZPcFW+kaFWeC54x3HjS0SePB0K3jz3Se7as7rOMkFDW3t35CF2uFcOVcYsJDL9LeghTXIGqfsC3r8+vxL+aYkVcPT49a2Usz6nyeIykrvqb1h366Y4XNSs=
  - secure: nen6ZLjOORrvvehqQMWp/UV18myoASV874OUI5vm8i/PKOEcPiTjRg7w495eBmfG223YC1siE88/29lr9CNeKGewSSOi2IxwQyEQyJUQhdnBcgaQIEAs2MW4p7eskhH1esqCXIKUUECMgMUwPieCrDB0CGLSZBVxMfxMnPR3CTg=
script:
- bundle exec rake db:create
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake spec
